namespace: "polyaxon"

rbac:
  enabled: true
ingress:
  enabled: false

serviceType: LoadBalancer

user:
  username: "root"
  email: "root@polyaxon.local"
  password: "laenk"

postgresql:
  persistence:
    enabled: true
    size: 10Gi

persistence:
  logs:
    enabled: true
    existingClaim: polyaxon-pvc-logs
    mountPath: "/logs"
    accessMode: ReadWriteMany
  repos:
    enabled: true
    existingClaim: polyaxon-pvc-repos
    mountPath: "/repos"
    accessMode: ReadWriteMany
  upload:
    enabled: true
    existingClaim: polyaxon-pvc-upload
    mountPath: "/upload"
    accessMode: ReadWriteMany
  data:
    data:
      enabled: true
      existingClaim: polyaxon-pvc-data
      mountPath: "/data"
      accessMode: ReadWriteMany
  outputs:
    outputs:
      enabled: true
      existingClaim: polyaxon-pvc-outputs
      mountPath: "/outputs"
      accessMode: ReadWriteMany

dirs:
  nvidia:
    lib: "/home/kubernetes/bin/nvidia/lib64"
    bin: "/home/kubernetes/bin/nvidia/bin"
    libcuda: "/home/kubernetes/bin/nvidia/lib64/libcuda.so.1"
  docker: "/var/run/docker.sock"

# This is where we mount nvidia on pods
mountPaths:
  nvidia:
    lib: ""
    bin: ""
    libcuda: ""
  docker: "/var/run/docker.sock"

tolerations:
  resourcesDeamon:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "present"
    effect: "NoSchedule"
