apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: model
spec:
  annotations:
    project_name: "Cartpole RL"
    deployment_version: v1
  name: cartpole
  oauth_key: "oauth-key"
  oauth_secret: "oauth-secret"
  predictors:
  - componentSpecs:
      - spec:
          containers:
          - image: "hypnosapos/cartpolerlremoteagent:571aef6"
            imagePullPolicy: Always
            name: cartpole
            resources:
              requests:
                memory: "2Mi"
          terminationGracePeriodSeconds: 20
    graph:
      children: []
      name: cartpole
      endpoint:
        type: "REST"
      type: "MODEL"
    name: cartpole
    replicas: 1
    annotations:
      predictor_version: v1
